### ISSUE TITLE
Where are the Luis' commits?

### ISSUE THREAD

**Issue by edysegura** [mauryrv/dm104-final-project#2]
![image](https://user-images.githubusercontent.com/5324414/29597806-76922b24-879b-11e7-81c2-b2eba0425ce1.png)

**Comment by luisjunior17** [comment]
Hi Edy,

I had problems to commit my codes in GitHub.
So, in order to not waste time with this question, we decided to make with the old way.
We know that is not the best way to develop, but it was necessary in order to not lose the deadline of project.

I was passing my code to Maury and he was committing here. That is the reason why there is no commit in my name on this repository.
As each one was responsible for different parts of the project, this didn't cause any clash or problem on code.

If you have another doubts, please contact us.
Thanks in advance!

Best Regards,
Luís Renato.

**Comment by edysegura** [comment]
I see, thank you for replying.
